resolver: lts-17.2
packages:
- .
- ../fei-base/
- ../fei-nn/
- ../tuple-ops
extra-deps:
- git: https://github.com/0xCM/type-combinators.git
  commit: 58167dd4017b666ff592bb9493b0570a054aabdb
- git: https://github.com/pierric/haskell-src-exts.git
  commit: 792ec73bc3b0e8d4aa2683af6b2a3fc03b5f8d95
extra-include-dirs:
- /home/jiasen/workspace/mxnet/build-1.7.0/include
extra-lib-dirs:
- /home/jiasen/workspace/mxnet/build-1.7.0
flags:
  fei-base:
    mxnet_geq_10700: true
  fei-nn:
    mxnet_geq_10700: true
  fei-einops:
    mxnet: true
